In [1]:
import pandas as pd

In [2]:
version = 'v4'

In [3]:
train_abst = pd.read_excel('./data/all_10_random_12000_262_train.xlsx')
train_abst = pd.DataFrame(train_abst['abstract'])

val_abst = pd.read_excel('./data/all_10_random_12000_262_val.xlsx')
val_abst = pd.DataFrame(val_abst['abstract'])

test_abst = pd.read_excel('./data/all_10_random_12000_262_test.xlsx')
test_abst = pd.DataFrame(test_abst['abstract'])



train_label = pd.read_excel('./data/rae_extra_all_{}_latent_vector_train.xlsx'.format(version))
train_label = train_label.drop(['Unnamed: 0'], axis=1)

val_label = pd.read_excel('./data/rae_extra_all_{}_latent_vector_val.xlsx'.format(version))
val_label = val_label.drop(['Unnamed: 0'], axis=1)

test_label = pd.read_excel('./data/rae_extra_all_{}_latent_vector_test.xlsx'.format(version))
test_label = test_label.drop(['Unnamed: 0'], axis=1)

In [4]:
train_abst

                                               abstract
0     본 연구는 청소년의 지역사회 및 가족, 학교생활과 관련한 사회자본의 중요성을 인식하...
1     최근 코로나19 사태로 인해 사람들 간의 물리적인 접촉을 최소화하려는 언택트 추세가...
2     글로벌경영이 보편화됨에 따라 이문화 조직(Cross-cultural Organiza...
3     본 연구는 청소년들이 학대경험에 대한 인식이 학업성취감에 미치는 영향과 스트레스를 ...
4     본 연구는 한국소비자들을 대상으로 중국 제품의 지각된 품질이 중국의 국가 및 제품 ...
...                                                 ...
2793  본 연구는 간호대학생의 임상실습 스트레스, 자아탄력성, 동료돌봄행위 정도를 파악하고...
2794  본 연구에서는 청소년이 지각하는 부모의 방임 및 학대와 우울 간의 관계에서 자아존중...
2795  경본 연구는 경찰청에서 조사한 2015~2016년도 경기남부지방경찰청 시흥경찰서의 ...
2796  본 연구의 목적은 대학생의 자기불일치와 사후반추사고가 우울 및 사회불안에 미치는 상...
2797  본 연구에서는 수업요소와 창의성교육 요소를 통합적으로 고려한 유아교사의 창의성교육 ...

[2798 rows x 1 columns]

In [5]:
val_abst

                                              abstract
0    본 연구는 테블릿 pc 어플리케이션을 사용한 인지훈련이 인지 손상이 있는 아급성 뇌...
1    기독교대학은 대학생의 스트레스 상황에서 영향을 조절하여 완충시켜주거나 적응을 도와주...
2    본 연구는 초등학생의 방과후 운동, 스마트폰 중독, 정신건강과의 관계를 탐색하기 위...
3    본 연구의 목적은 마을교육의 방과후학교 참여 의의를 살펴보고 학교와 마을교육 간의 ...
4    오늘날 고령화뿐만 아니라 복합적 욕구를 가진 인구의 증가는 사회적 돌봄의 필요성을 ...
..                                                 ...
927  본 연구는 직무스트레스 요인이 번영과 직무열의에 영향을 미치는 과정에 있어서 문화 ...
928  본 연구는 청소년의 ADHD 성향과 자기유능감 및 학교생활적응의 관계에서 실행기능 ...
929  한국의 개인사업자수는 2017년 기준 560만명을 넘어섰는데, 그에 따라 경쟁이 치...
930  본 연구는 수원정신보건센터를 방문한 아동들을 대상으로 1) 스마트폰 중독에 따른 정...
931  본 연구는 국내의 장애학생 고등교육과 관련된 연구논문들을 분석하여 전반적인 연구동향...

[932 rows x 1 columns]

In [6]:
test_abst

                                              abstract
0    본 연구의 목적은 지금까지 개발된 초등학교 안전지도에 대한 비판적 차원의 분석, 검...
1    본 연구의 목적은 간호사의 여가활동 유형을 분류하고 실증적 분석을 실시하여 여가활동...
2    중국 소비자들의 한국화장품에 대한 소비행태에 대한 연구들은 꾸준하게 연구되어져 왔다...
3    본 연구의 목적은 북한이탈주민 부부의 부부관계 적응과 남한사회 적응 과정을 탐색하는...
4    본 연구의 목적은 음악과 건강 체조 프로그램이 재가노인의 우울, 자아존중감 및 인지...
..                                                 ...
927  본 연구의 목적은 선행연구를 기초로 하여 호텔에 적합한 다차원적인 서비스 편의성을 ...
928  최근 IT 기술의 발달과 함께 소셜 미디어, 모바일 단말기, 사물인터넷과 같은 다양...
929  본 연구는 다차원적 진로정체감 모형을 사용하여 대학생의 진로정체감 지위(성취, 유실...
930  본 연구의 목적은 노인의 자살생각에 영향을 미치는 개인적 요인을 분석함으로써 노인자...
931  2014년 한국 헌법재판소는 문화콘텐츠 산업 관련 중요한 판결을 내렸다. 여성가족부...

[932 rows x 1 columns]

In [7]:
train_label

             0         1         2         3
0     5.194959  0.463620  3.099519  1.837639
1     2.523835  3.260611  1.669686  3.370940
2     0.930321  0.542420  1.852430  0.000000
3     5.194959  0.463620  3.099519  1.837639
4     4.333861  3.978497  3.662714  3.577977
...        ...       ...       ...       ...
2793  4.946594  8.686300  1.476334  0.000000
2794  7.886700  2.730818  1.936125  2.332378
2795  1.834378  1.115448  4.501013  3.099241
2796  7.886700  2.730818  1.936125  2.332378
2797  1.561563  1.182006  2.323821  1.482143

[2798 rows x 4 columns]

In [8]:
val_label

            0         1         2         3
0    4.252167  2.948070  0.193734  2.841667
1    4.448070  5.104998  1.674422  0.211541
2    4.941952  1.189352  0.948080  5.824813
3    7.061509  4.723454  1.920044  4.697660
4    2.356642  6.174630  5.023724  1.891224
..        ...       ...       ...       ...
927  2.117849  2.717265  1.860312  0.000000
928  4.311187  1.612342  2.545564  1.304350
929  2.356642  6.174629  5.023723  1.891224
930  3.285078  3.259609  2.390505  1.122444
931  2.872831  2.474819  1.055902  2.022084

[932 rows x 4 columns]

In [9]:
test_label

            0         1         2         3
0    2.356642  6.174630  5.023724  1.891224
1    1.728056  2.490819  1.481277  0.309363
2    0.569367  2.411349  0.669784  2.912357
3    1.272908  0.038271  3.581591  5.395686
4    5.353525  2.865519  0.000000  1.439444
..        ...       ...       ...       ...
927  0.000000  1.773600  0.121333  4.443259
928  0.000000  3.431511  3.441139  2.680054
929  3.078681  0.956077  1.338593  0.836499
930  7.714356  5.515837  1.598979  2.919135
931  1.897139  2.673828  1.905965  2.324860

[932 rows x 4 columns]

In [10]:
train = pd.concat([train_abst, train_label], axis=1)
train

,abstract,0,1,2,3
0,"본 연구는 청소년의 지역사회 및 가족, 학교생활과 관련한 사회자본의 중요성을 인식하...",5.194959,0.463620,3.099519,1.837639
1,최근 코로나19 사태로 인해 사람들 간의 물리적인 접촉을 최소화하려는 언택트 추세가...,2.523835,3.260611,1.669686,3.370940
2,글로벌경영이 보편화됨에 따라 이문화 조직(Cross-cultural Organiza...,0.930321,0.542420,1.852430,0.000000
3,본 연구는 청소년들이 학대경험에 대한 인식이 학업성취감에 미치는 영향과 스트레스를 ...,5.194959,0.463620,3.099519,1.837639
4,본 연구는 한국소비자들을 대상으로 중국 제품의 지각된 품질이 중국의 국가 및 제품 ...,4.333861,3.978497,3.662714,3.577977
...,...,...,...,...,...
2793,"본 연구는 간호대학생의 임상실습 스트레스, 자아탄력성, 동료돌봄행위 정도를 파악하고...",4.946594,8.686300,1.476334,0.000000
2794,본 연구에서는 청소년이 지각하는 부모의 방임 및 학대와 우울 간의 관계에서 자아존중...,7.886700,2.730818,1.936125,2.332378
2795,경본 연구는 경찰청에서 조사한 2015~2016년도 경기남부지방경찰청 시흥경찰서의 ...,1.834378,1.115448,4.501013,3.099241
2796,본 연구의 목적은 대학생의 자기불일치와 사후반추사고가 우울 및 사회불안에 미치는 상...,7.886700,2.730818,1.936125,2.332378
2797,본 연구에서는 수업요소와 창의성교육 요소를 통합적으로 고려한 유아교사의 창의성교육 ...,1.561563,1.182006,2.323821,1.482143

In [11]:
val = pd.concat([val_abst, val_label], axis=1)
val

,abstract,0,1,2,3
0,본 연구는 테블릿 pc 어플리케이션을 사용한 인지훈련이 인지 손상이 있는 아급성 뇌...,4.252167,2.948070,0.193734,2.841667
1,기독교대학은 대학생의 스트레스 상황에서 영향을 조절하여 완충시켜주거나 적응을 도와주...,4.448070,5.104998,1.674422,0.211541
2,"본 연구는 초등학생의 방과후 운동, 스마트폰 중독, 정신건강과의 관계를 탐색하기 위...",4.941952,1.189352,0.948080,5.824813
3,본 연구의 목적은 마을교육의 방과후학교 참여 의의를 살펴보고 학교와 마을교육 간의 ...,7.061509,4.723454,1.920044,4.697660
4,오늘날 고령화뿐만 아니라 복합적 욕구를 가진 인구의 증가는 사회적 돌봄의 필요성을 ...,2.356642,6.174630,5.023724,1.891224
...,...,...,...,...,...
927,본 연구는 직무스트레스 요인이 번영과 직무열의에 영향을 미치는 과정에 있어서 문화 ...,2.117849,2.717265,1.860312,0.000000
928,본 연구는 청소년의 ADHD 성향과 자기유능감 및 학교생활적응의 관계에서 실행기능 ...,4.311187,1.612342,2.545564,1.304350
929,"한국의 개인사업자수는 2017년 기준 560만명을 넘어섰는데, 그에 따라 경쟁이 치...",2.356642,6.174629,5.023723,1.891224
930,본 연구는 수원정신보건센터를 방문한 아동들을 대상으로 1) 스마트폰 중독에 따른 정...,3.285078,3.259609,2.390505,1.122444
931,본 연구는 국내의 장애학생 고등교육과 관련된 연구논문들을 분석하여 전반적인 연구동향...,2.872831,2.474819,1.055902,2.022084

In [12]:
test = pd.concat([test_abst, test_label], axis=1)
test

,abstract,0,1,2,3
0,"본 연구의 목적은 지금까지 개발된 초등학교 안전지도에 대한 비판적 차원의 분석, 검...",2.356642,6.174630,5.023724,1.891224
1,본 연구의 목적은 간호사의 여가활동 유형을 분류하고 실증적 분석을 실시하여 여가활동...,1.728056,2.490819,1.481277,0.309363
2,중국 소비자들의 한국화장품에 대한 소비행태에 대한 연구들은 꾸준하게 연구되어져 왔다...,0.569367,2.411349,0.669784,2.912357
3,본 연구의 목적은 북한이탈주민 부부의 부부관계 적응과 남한사회 적응 과정을 탐색하는...,1.272908,0.038271,3.581591,5.395686
4,"본 연구의 목적은 음악과 건강 체조 프로그램이 재가노인의 우울, 자아존중감 및 인지...",5.353525,2.865519,0.000000,1.439444
...,...,...,...,...,...
927,본 연구의 목적은 선행연구를 기초로 하여 호텔에 적합한 다차원적인 서비스 편의성을 ...,0.000000,1.773600,0.121333,4.443259
928,"최근 IT 기술의 발달과 함께 소셜 미디어, 모바일 단말기, 사물인터넷과 같은 다양...",0.000000,3.431511,3.441139,2.680054
929,"본 연구는 다차원적 진로정체감 모형을 사용하여 대학생의 진로정체감 지위(성취, 유실...",3.078681,0.956077,1.338593,0.836499
930,본 연구의 목적은 노인의 자살생각에 영향을 미치는 개인적 요인을 분석함으로써 노인자...,7.714356,5.515837,1.598979,2.919135
931,2014년 한국 헌법재판소는 문화콘텐츠 산업 관련 중요한 판결을 내렸다. 여성가족부...,1.897139,2.673828,1.905965,2.324860

In [13]:
train.to_excel('./data/rae_extra_all_{}_train.xlsx'.format(version))
val.to_excel('./data/rae_extra_all_{}_val.xlsx'.format(version))
test.to_excel('./data/rae_extra_all_{}_test.xlsx'.format(version))